### ISSUE TITLE
建议包含或者增加base64算法，消息摘要算法，DES和DESede，AES，PBE，RSA和数字签名算法

### ISSUE THREAD

**Issue by passerbyo** [simplephp/encrypt-decrypt#4]

**Comment by simplephp** [comment]
感谢你的建议，针对对称加密来说，从安全性、资源消耗、运算速度、消耗时间综合来看 AES 都是值得选择的对称加密方式，故只实现了AES相关([README.md](https://github.com/simplephp/encrypt-decrypt#readme))，后续可以添加 base64 en/decode ,RSA 非对称加密
